# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

assembly_info:
  patch: true
  file: '**\**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

  - path: src\JSaraiva.Foursquare.SearchPlaces.Client\bin\$(configuration)\*.dll
    name: 'package dll'

  - path: src\**\*.nupkg
    name: 'package nuget'
