# version format
version: 1.1.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: '**\**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release
configuration: Release

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: src/JSaraiva.Foursquare.SearchPlaces.Client/bin/$(configuration)
    name: JSaraiva.Foursquare.SearchPlaces.Client.dll
