version: 1.0.{build}

environment:
  my_folder: '%APPVEYOR_BUILD_FOLDER%\test101'

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
